bug fixed - error on edit qty
error: when the user change the qty, the qty available was not updated

solution: set method has been added getting the same info from qty field

-> log has been improved